export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as WrappedMap} from './Map'
export {default as Gallery} from './Home/Gallery'
export {default as ProductSlider} from './Home/ProductSlider'
export {default as ProductCard} from './ProductCard/index'
export {default as LoadingCard} from './ProductCard/LoadingCard'
export {default as Filters} from './Store/filters'